language: java

dist: xenial

python: "3.7"

install: pip install requests==2.25.1  

script: bash -c "source ./configs/build-travis.sh && ./run.sh"

deploy:
  skip_cleanup: true
  provider: script
  script: . ./configs/travis.sh && . ./configs/deploy.sh
  on:
    branch: master
