language: java

dist: xenial

script:
  - . ./configs/travis.sh
  - ./run.sh  

deploy:
  skip_cleanup: true
  provider: script
  script: . ./configs/travis.sh && . ./configs/deploy.sh
  on:
    branch: master
